spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml
  datasource:
    url: jdbc:postgresql://host.docker.internal:5433/payments
    username: program
    password: test